name: CI Pipeline

on:
  push:
    branches: [ "main", "oussama", "feature/*" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify Content
        run: grep -q "Découvrez nos nouveautés" index.html
